package jp.ac.kyoto_u.kueps.naruse_utils;

import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;
import javax.print.attribute.standard.OrientationRequested;

/**
 * 互換用の簡易スタブ。
 * 元実装は PostScript(.ps) を書き出していた可能性がありますが、
 * ここでは「機能は限定（実質無効）でも落ちない」ことを優先します。
 *
 * STubeFrame 側で new PSExporter(...); しているだけならコンパイルが通ります。
 * もし export() を呼んでいる場合でも、説明文を .ps に書いて終わります。
 */
public class PSExporter {

    private final Object target;
    private final File file;

    public PSExporter(Component graph, File file) {
        this.target = graph;
        this.file = file;
    }

    public PSExporter(Component[] graphs, File file) {
        this.target = graphs;
        this.file = file;
    }

    public PSExporter(List<? extends Component> graphs, File file) {
        this.target = graphs;
        this.file = file;
    }

    // 最後の保険：型が合わなくても受け取れるように
    public PSExporter(Object anything, File file) {
        this.target = anything;
        this.file = file;
    }

    public void export() throws IOException {
        if (file == null) return;

        // 本物のPS出力はここでは行わず、代替メッセージを書くだけにする
        try (FileWriter fw = new FileWriter(file)) {
            fw.write("%!PS-Adobe-3.0\n");
            fw.write("% This is a placeholder PostScript generated by a compatibility stub.\n");
            fw.write("% Original PS exporting is not implemented in this port.\n");
            fw.write("%%EOF\n");
        }

        // GUIから呼ばれた場合に分かりやすく通知
        SwingUtilities.invokeLater(() ->
                JOptionPane.showMessageDialog(
                        null,
                        "PS export is not implemented in this updated build.\nA placeholder file was written.",
                        "PS Export",
                        JOptionPane.INFORMATION_MESSAGE
                )
        );
    }
    private OrientationRequested orientation = null;
    
    public void setOrientation(OrientationRequested o) {
        this.orientation = o; // 今回は保持するだけ（互換のため）
    }

    public void exportGraphic() throws IOException {
        export(); // 互換のため export() を呼ぶ
    }
}
